import { Injectable } from '@angular/core';
import { EquipoClasificacion } from '../models/clasificacion.model';

@Injectable({
  providedIn: 'root',
})
export class ClasificacionService {
  constructor() {}

  getClasificacion(): EquipoClasificacion[] {
    return [
      {
        posicion: 1,
        nombre: 'Las Rozas',
        escudo: 'assets/escudos/LasRozas.png',
        puntos: 45,
        partidosJugados: 18,
        partidosGanados: 14,
        partidosEmpatados: 3,
        partidosPerdidos: 1,
        golesFavor: 42,
        golesContra: 10,
        diferenciaGoles: 32,
        forma: ['G', 'G', 'G', 'E', 'G'],
      },
      {
        posicion: 2,
        nombre: 'Rayo Majadahonda',
        escudo: 'assets/escudos/RayoMajadahonda.png',
        puntos: 42,
        partidosJugados: 18,
        partidosGanados: 13,
        partidosEmpatados: 3,
        partidosPerdidos: 2,
        golesFavor: 38,
        golesContra: 15,
        diferenciaGoles: 23,
        forma: ['G', 'G', 'P', 'G', 'G'],
      },
      {
        posicion: 3,
        nombre: 'UD Villalba',
        escudo: 'assets/escudos/logo-udvillalba.png',
        puntos: 38,
        partidosJugados: 18,
        partidosGanados: 11,
        partidosEmpatados: 5,
        partidosPerdidos: 2,
        golesFavor: 30,
        golesContra: 12,
        diferenciaGoles: 18,
        forma: ['E', 'G', 'G', 'E', 'G'],
      },
      {
        posicion: 4,
        nombre: 'Inter Majadahonda',
        escudo: 'assets/escudos/InterMajadahonda.png',
        puntos: 35,
        partidosJugados: 18,
        partidosGanados: 10,
        partidosEmpatados: 5,
        partidosPerdidos: 3,
        golesFavor: 28,
        golesContra: 18,
        diferenciaGoles: 10,
        forma: ['P', 'G', 'G', 'G', 'E'],
      },
      {
        posicion: 5,
        nombre: 'Olympia',
        escudo: 'assets/escudos/olympia.png',
        puntos: 30,
        partidosJugados: 18,
        partidosGanados: 9,
        partidosEmpatados: 3,
        partidosPerdidos: 6,
        golesFavor: 25,
        golesContra: 22,
        diferenciaGoles: 3,
        forma: ['G', 'E', 'P', 'G', 'P'],
      },
      {
        posicion: 6,
        nombre: 'Villanueva',
        escudo: 'assets/escudos/VILLANUEVA.png',
        puntos: 28,
        partidosJugados: 18,
        partidosGanados: 8,
        partidosEmpatados: 4,
        partidosPerdidos: 6,
        golesFavor: 24,
        golesContra: 20,
        diferenciaGoles: 4,
        forma: ['E', 'E', 'G', 'P', 'G'],
      },
      {
        posicion: 7,
        nombre: 'Nuevo Boadilla',
        escudo: 'assets/escudos/NuevoBoadilla.png',
        puntos: 22,
        partidosJugados: 18,
        partidosGanados: 6,
        partidosEmpatados: 4,
        partidosPerdidos: 8,
        golesFavor: 20,
        golesContra: 28,
        diferenciaGoles: -8,
        forma: ['P', 'P', 'G', 'E', 'P'],
      },
      {
        posicion: 8,
        nombre: 'AD Castilla',
        escudo: 'assets/escudos/ADCastilla.png',
        puntos: 18,
        partidosJugados: 18,
        partidosGanados: 5,
        partidosEmpatados: 3,
        partidosPerdidos: 10,
        golesFavor: 18,
        golesContra: 35,
        diferenciaGoles: -17,
        forma: ['G', 'P', 'P', 'P', 'P'],
      },
      {
        posicion: 9,
        nombre: 'CDG',
        escudo: 'assets/escudos/cdg.png',
        puntos: 15,
        partidosJugados: 18,
        partidosGanados: 4,
        partidosEmpatados: 3,
        partidosPerdidos: 11,
        golesFavor: 15,
        golesContra: 32,
        diferenciaGoles: -17,
        forma: ['P', 'G', 'P', 'E', 'P'],
      },
      {
        posicion: 10,
        nombre: 'Colmenarejo',
        escudo: 'assets/escudos/Colmenarejo.png',
        puntos: 10,
        partidosJugados: 18,
        partidosGanados: 2,
        partidosEmpatados: 4,
        partidosPerdidos: 12,
        golesFavor: 12,
        golesContra: 40,
        diferenciaGoles: -28,
        forma: ['P', 'P', 'E', 'P', 'P'],
      },
    ];
  }
}
